import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { DessertProvider } from '@/context/DessertContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Sugar Whisk Desserts',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <DessertProvider>{children}</DessertProvider>
      </body>
    </html>
  );
}
